spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${JAWSDB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.data.rest.base-path=/api

allowed.origins = ${ALLOWED_ORIGIN}

spring.data.rest.detection-strategy = ANNOTATED

okta.oauth2.client-id=${OKTA_ID}
okta.oauth2.client-secret=${OKTA_SECRET}
okta.oauth2.issuer=${OKTA_ISSUER}


# Server web port
# server.port=8443
# server.port=9898

# Enable HTTPS support (only accept HTTPS requests)
# server.ssl.enabled=true

# # Alias that identifies the key in the key store
# server.ssl.key-alias=luv2code

# # Keystore location
# server.ssl.key-store=classpath:luv2code-keystore.p12

# # Keystore password
# server.ssl.key-store-password=secret

# # Keystore format
# server.ssl.key-store-type=PKCS12

# Stripe
stripe.key.secret=${STRIPE_SECRET}

#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true